# Generated by Django 5.0.2 on 2024-02-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=300, null=True)),
                ('a', models.CharField(blank=True, max_length=300, null=True)),
                ('b', models.CharField(blank=True, max_length=300, null=True)),
                ('c', models.CharField(blank=True, max_length=300, null=True)),
                ('d', models.CharField(blank=True, max_length=300, null=True)),
                ('answer', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
